/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.apparquivotexto;

/**
 *
 * @author afonsvfdeb
 */
public class InserirArq extends javax.swing.JInternalFrame {
    
    //referencia para o mesmo objeto CreateTextFile que a MainForm usa,
    //para gravar no MESMO arquivo que foi aberto por lá
    private CreateTextFile app;
    
    /**
     * Creates new form AbrirArq
     */
    public InserirArq() {
        initComponents();
    }
    
    /**
     * Construtor usado pela MainForm, recebe a instancia do CreateTextFile
     * (o arquivo já aberto) para poder gravar os registros nela.
     */
    public InserirArq(CreateTextFile app) {
        initComponents();
        this.app = app;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTsaldo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTnConta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTPnome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTUnome = new javax.swing.JTextField();
        jBinserir = new javax.swing.JButton();

        setClosable(true);
        setResizable(true);

        jLabel1.setText("N conta");

        jTsaldo.addActionListener(this::jTsaldoActionPerformed);

        jLabel2.setText("F nome");

        jTnConta.addActionListener(this::jTnContaActionPerformed);

        jLabel3.setText("U nome");

        jTPnome.addActionListener(this::jTPnomeActionPerformed);

        jLabel4.setText("Saldo");

        jTUnome.addActionListener(this::jTUnomeActionPerformed);

        jBinserir.setText("Inserir");
        jBinserir.addActionListener(this::jBinserirActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTsaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTUnome))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTnConta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTPnome, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(jBinserir)))
                .addContainerGap(221, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jTnConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jTPnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTUnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTsaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jBinserir)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTsaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTsaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTsaldoActionPerformed

    private void jTnContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTnContaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTnContaActionPerformed

    private void jTPnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTPnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTPnomeActionPerformed

    private void jTUnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTUnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTUnomeActionPerformed

    private void jBinserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBinserirActionPerformed
        
        if(app == null){
            javax.swing.JOptionPane.showMessageDialog(this, "Arquivo nao foi aberto. Use o menu Arquivo > Open file primeiro.");
            return;
        }
        
        Integer cod;
        String pnome, unome;
        Double saldo;
        
        try{
            cod = Integer.parseInt(jTnConta.getText().trim());
            pnome = jTPnome.getText().trim();
            unome = jTUnome.getText().trim();
            saldo = Double.parseDouble(jTsaldo.getText().trim());
        }catch(NumberFormatException ex){
            javax.swing.JOptionPane.showMessageDialog(this, "Digite as informacoes corretamente!\nN. da conta e Saldo devem ser numeros.");
            return;
        }
        
        //grava o registro usando o mesmo CreateTextFile (mesmo arquivo) da MainForm
        boolean gravou = app.addRecord(cod, pnome, unome, saldo);
        
        if(gravou){
            javax.swing.JOptionPane.showMessageDialog(this, "Registro inserido com sucesso!");
            
            //limpa os campos para o proximo registro
            jTnConta.setText("");
            jTPnome.setText("");
            jTUnome.setText("");
            jTsaldo.setText("");
        }

    }//GEN-LAST:event_jBinserirActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBinserir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTPnome;
    private javax.swing.JTextField jTUnome;
    private javax.swing.JTextField jTnConta;
    private javax.swing.JTextField jTsaldo;
    // End of variables declaration//GEN-END:variables
}
