/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.appempregados;

/**
 *
 * @author afonsvfdeb
 */
public class ConsultarEmpregado extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConsultarEmpregado
     */
    public ConsultarEmpregado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        JRtodos = new javax.swing.JRadioButton();
        JRclt = new javax.swing.JRadioButton();
        JRhorista = new javax.swing.JRadioButton();
        jBconsultar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        buttonGroup1.add(JRtodos);
        JRtodos.setSelected(true);
        JRtodos.setText("Todos");
        JRtodos.addActionListener(this::JRtodosActionPerformed);

        buttonGroup1.add(JRclt);
        JRclt.setText("CLT");
        JRclt.addActionListener(this::JRcltActionPerformed);

        buttonGroup1.add(JRhorista);
        JRhorista.setText("Horista");

        jBconsultar.setText("Consultar");
        jBconsultar.addActionListener(this::jBconsultarActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "CPF", "Endereco", "Salario Bruto", "Nhoras", "Preco hora"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBconsultar)
                    .addComponent(JRhorista)
                    .addComponent(JRtodos)
                    .addComponent(JRclt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 721, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(JRtodos)
                .addGap(18, 18, 18)
                .addComponent(JRclt)
                .addGap(18, 18, 18)
                .addComponent(JRhorista)
                .addGap(18, 18, 18)
                .addComponent(jBconsultar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JRtodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRtodosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JRtodosActionPerformed

    private void JRcltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRcltActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JRcltActionPerformed

    private void jBconsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBconsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBconsultarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton JRclt;
    private javax.swing.JRadioButton JRhorista;
    private javax.swing.JRadioButton JRtodos;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBconsultar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
