/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.main.apparquivoserializado;

import javax.swing.JOptionPane;

/**
 *
 * @author afonsvfdeb
 */
public class Escrever extends javax.swing.JInternalFrame {

    /**
     * Creates new form Escrever
     */
    public Escrever() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        conta = new javax.swing.JTextField();
        pNome = new javax.swing.JTextField();
        Unome = new javax.swing.JTextField();
        saldo = new javax.swing.JTextField();
        jBinserir = new javax.swing.JButton();

        setClosable(true);

        conta.setText("conta");
        conta.addActionListener(this::contaActionPerformed);

        pNome.setText("Primeiro nome");

        Unome.setText("ultimo nome");
        Unome.addActionListener(this::UnomeActionPerformed);

        saldo.setText("saldo");

        jBinserir.setText("Inserir");
        jBinserir.addActionListener(this::jBinserirActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Unome)
                    .addComponent(pNome)
                    .addComponent(saldo)
                    .addComponent(conta, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jBinserir)))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(conta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Unome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBinserir)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contaActionPerformed

    private void UnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UnomeActionPerformed

    private void jBinserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBinserirActionPerformed
        // TODO add your handling code here:
        WriteRandomFile escrever = new WriteRandomFile();
        
        Integer numConta = Integer.parseInt(conta.getText());
        String nome = pNome.getText();
        String sobrenome = Unome.getText();
        Double valorSaldo = Double.parseDouble(saldo.getText());
        
        escrever.openFile();
        escrever.addRecords(numConta, nome, sobrenome, valorSaldo);
        escrever.closeFile();
            JOptionPane.showMessageDialog(rootPane, "Registro inserido!");
        
    }//GEN-LAST:event_jBinserirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Unome;
    private javax.swing.JTextField conta;
    private javax.swing.JButton jBinserir;
    private javax.swing.JTextField pNome;
    private javax.swing.JTextField saldo;
    // End of variables declaration//GEN-END:variables
}
