/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.appcrud;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author afonsvfdeb
 */
public class CadastroAluno extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastroAluno
     */
    private Connection con;
    private Statement stm;
    private ResultSet res;

    
    public CadastroAluno() {
        
        
        initComponents();
        listarCursos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcpf = new javax.swing.JLabel();
        JTextCPF = new javax.swing.JTextField();
        jNome = new javax.swing.JLabel();
        jTextUnome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextPnome = new javax.swing.JTextField();
        jBcadastrar = new javax.swing.JButton();
        jComboCurso = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastro de aluno");

        jcpf.setText("CPF");

        jNome.setText("Nome");

        jTextUnome.addActionListener(this::jTextUnomeActionPerformed);

        jLabel3.setText("Ultimo nome");

        jTextPnome.addActionListener(this::jTextPnomeActionPerformed);

        jBcadastrar.setText("Cadastrar");
        jBcadastrar.addActionListener(this::jBcadastrarActionPerformed);

        jComboCurso.addActionListener(this::jComboCursoActionPerformed);

        jLabel1.setText("Curso");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(jNome)
                    .addComponent(jcpf)
                    .addComponent(jTextPnome)
                    .addComponent(JTextCPF)
                    .addComponent(jTextUnome, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboCurso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jBcadastrar)
                                .addGap(0, 28, Short.MAX_VALUE)))
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcpf)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTextCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextPnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBcadastrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextUnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextPnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPnomeActionPerformed

    private void jTextUnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextUnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextUnomeActionPerformed

    private void jBcadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcadastrarActionPerformed

        DAO banco = new DAO();
        String comando = "INSERT INTO alunos VALUES ('"+JTextCPF.getText()+"', '"+jTextPnome.getText()+"','"+
            jTextUnome.getText()+"',"+(jComboCurso.getSelectedIndex()+1)+")";
        banco.inserir(comando);
        
        //mostrar sucesso
        JOptionPane.showMessageDialog(rootPane, "Registro inserido");
        
        //limpar texto
        JTextCPF.setText("");
        jTextPnome.setText("");
        jTextUnome.setText("");
        
    }//GEN-LAST:event_jBcadastrarActionPerformed

    private void jComboCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboCursoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTextCPF;
    private javax.swing.JButton jBcadastrar;
    private javax.swing.JComboBox<String> jComboCurso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jNome;
    private javax.swing.JTextField jTextPnome;
    private javax.swing.JTextField jTextUnome;
    private javax.swing.JLabel jcpf;
    // End of variables declaration//GEN-END:variables

    private void listarCursos() {

        try {
            String comando = "SELECT * FROM cursos";
            //instanciar um objeto DAO
            DAO banco = new DAO();
            //conectar no banco
            res = banco.consultar(comando); //LISTA DE REGISTROS
            //Ao comboBox
            
            while(res.next()){ //AINDA TEM REGISTROS PRA LER? SIM -> LISTAR, NAO -> RETORNA FALSE
                
                jComboCurso.addItem(res.getString("descr"));
                
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "erro ao consultar!");
        }
       
}
}
