/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.appcrud;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author afonsvfdeb
 */
public class ConsultarAlunos extends javax.swing.JInternalFrame {

    private Connection con;
    private Statement stm;
    private ResultSet res;
    /**
     * Creates new form ConsultarAlunos
     */
    public ConsultarAlunos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jBconsulta = new javax.swing.JButton();
        jBatualizar = new javax.swing.JButton();
        jBexcluir = new javax.swing.JButton();

        setClosable(true);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CPF", "Nome", "Sobrenome", "Curso id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jBconsulta.setText("Consulta");
        jBconsulta.addActionListener(this::jBconsultaActionPerformed);

        jBatualizar.setText("Atualizar");
        jBatualizar.addActionListener(this::jBatualizarActionPerformed);

        jBexcluir.setText("Excluir");
        jBexcluir.addActionListener(this::jBexcluirActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBconsulta, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jBexcluir)
                        .addComponent(jBatualizar)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jBconsulta)
                .addGap(18, 18, 18)
                .addComponent(jBatualizar)
                .addGap(18, 18, 18)
                .addComponent(jBexcluir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBconsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBconsultaActionPerformed
   
        // TODO add your handling code here:
        
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        //limpar as linhas do jtable
        
        model.setNumRows(0);
        String comando = "SELECT * FROM alunos";
        
        //objeto DAO para manipular banco
        
        DAO banco = new DAO();
        //conectar ao banco
        //executar a consulta;
        res = banco.consultar(comando); //res guarda o conteudo de saida da consulta
        try {
            while(res.next()){
                model.addRow(new Object[]{res.getString("cpf"),
                res.getString("pnome"),
                res.getString("unome"),
                res.getString("cursoID")
                
                });
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao consultar registro!");
        }
    }//GEN-LAST:event_jBconsultaActionPerformed

    private void jBatualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBatualizarActionPerformed
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        
        String comando = "UPDATE alunos SET " +
                 "pnome = '" + model.getValueAt(jTable1.getSelectedRow(), 1) + "', " +
                 "snome = '" + model.getValueAt(jTable1.getSelectedRow(), 2) + "' " +
                 "WHERE cpf = '" + model.getValueAt(jTable1.getSelectedRow(), 0) + "'";
        
        DAO banco = new DAO() ;
        banco.atualizar(comando);
        banco.consultar(comando);//mostrar dados atualizados
    }//GEN-LAST:event_jBatualizarActionPerformed

    private void jBexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBexcluirActionPerformed
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();

        String comando = "DELETE FROM alunos WHERE cpf='"+
                model.getValueAt(jTable1.getSelectedRow(), 0)+"'";
        
        DAO banco = new DAO();
        banco.excluir(comando);
        
        String comando2 = "SELECT * FROM alunos";
        banco.consultar(comando2);
        
    }//GEN-LAST:event_jBexcluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBatualizar;
    private javax.swing.JButton jBconsulta;
    private javax.swing.JButton jBexcluir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
