/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package com.mycompany.appcrud;

/**
 *
 * @author afonsvfdeb
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        MenuArquivo = new javax.swing.JMenu();
        itemMenuSair = new javax.swing.JMenuItem();
        MenuCadastro = new javax.swing.JMenu();
        itemMenuCurso = new javax.swing.JMenuItem();
        itemMenuAluno = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        itemMenuCcurso = new javax.swing.JMenuItem();
        itemMenuCaluno = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MenuArquivo.setMnemonic('f');
        MenuArquivo.setText("Arquivo");

        itemMenuSair.setMnemonic('x');
        itemMenuSair.setText("Sair");
        itemMenuSair.addActionListener(this::itemMenuSairActionPerformed);
        MenuArquivo.add(itemMenuSair);

        menuBar.add(MenuArquivo);

        MenuCadastro.setMnemonic('e');
        MenuCadastro.setText("Cadastro");

        itemMenuCurso.setMnemonic('t');
        itemMenuCurso.setText("Cadastrar curso");
        itemMenuCurso.addActionListener(this::itemMenuCursoActionPerformed);
        MenuCadastro.add(itemMenuCurso);

        itemMenuAluno.setMnemonic('y');
        itemMenuAluno.setText("Cadastrar aluno");
        itemMenuAluno.addActionListener(this::itemMenuAlunoActionPerformed);
        MenuCadastro.add(itemMenuAluno);

        menuBar.add(MenuCadastro);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Consulta");

        itemMenuCcurso.setMnemonic('c');
        itemMenuCcurso.setText("Curso");
        itemMenuCcurso.addActionListener(this::itemMenuCcursoActionPerformed);
        helpMenu.add(itemMenuCcurso);

        itemMenuCaluno.setMnemonic('a');
        itemMenuCaluno.setText("Aluno");
        itemMenuCaluno.addActionListener(this::itemMenuCalunoActionPerformed);
        helpMenu.add(itemMenuCaluno);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 765, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_itemMenuSairActionPerformed

    private void itemMenuCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuCursoActionPerformed

        CadastroCurso form = new CadastroCurso();
        desktopPane.add(form);
        form.setVisible(true);

    }//GEN-LAST:event_itemMenuCursoActionPerformed

    private void itemMenuCcursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuCcursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemMenuCcursoActionPerformed

    private void itemMenuAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuAlunoActionPerformed

        CadastroAluno form = new CadastroAluno();
        desktopPane.add(form);
        form.setVisible(true);

    }//GEN-LAST:event_itemMenuAlunoActionPerformed

    private void itemMenuCalunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuCalunoActionPerformed
        // TODO add your handling code here:
        ConsultarAlunos form = new ConsultarAlunos();
        desktopPane.add(form);
        form.setVisible(true);
        
    }//GEN-LAST:event_itemMenuCalunoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuArquivo;
    private javax.swing.JMenu MenuCadastro;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem itemMenuAluno;
    private javax.swing.JMenuItem itemMenuCaluno;
    private javax.swing.JMenuItem itemMenuCcurso;
    private javax.swing.JMenuItem itemMenuCurso;
    private javax.swing.JMenuItem itemMenuSair;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
